apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod   # ✅ Matches the name used in Jenkins script
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      containers:
      - name: predictor
        image: selvaganapathi1009/car-price-predictor:latest  # ✅ Ensuring correct image
        imagePullPolicy: Always
        ports:
        - containerPort: 8000  # ✅ Matches Django/Flask app port
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: accessKey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: secretKey
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
          requests:
            memory: "256Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: predictor-service
spec:
  selector:
    app: predictor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000  # ✅ Ensuring traffic reaches the right container port
  type: LoadBalancer
