apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod  # ✅ Matches Jenkins script
spec:
  replicas: 3  # ✅ Ensures multiple pods for load balancing
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: selvaganapathi1009/newimage:latest  # ✅ Ensures correct image
        imagePullPolicy: Always
        ports:
        - containerPort: 80  # ✅ Ensures the container listens on the correct port
