apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod   # ✅ Changed from car-price-predictor to loadbalancer-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      containers:
      - name: predictor
        image: selvaganapathi1009/car-price-predictor
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: predictor-service
spec:
  selector:
    app: predictor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
